### ISSUE TITLE
Querying all table data should be avoided

### ISSUE THREAD

**Issue by hawklorry** [shahviransh/ECCC-IMWEBs-Viewer-Backend#1]
https://github.com/shahviransh/ECCC-IMWEBs-Viewer-Backend/blob/73e1021257d08ed7b77af4cbc3ffe8ef8d2795fe/backend/app.py#L227

**Comment by shahviransh** [comment]
The commit [cd7a050](https://github.com/shahviransh/ECCC-IMWEBs-Viewer-Backend/commit/cd7a0505349ed00eddf8bf4a02e640bfd1222b35) solved the issue.
